language: go
go:
  - 1.8.x
  - 1.9.x
  - 1.10.x
  - tip

matrix:
  allow_failures:
    - go: tip

install:
  - go get -u golang.org/x/lint/golint
  - go get -t -v ./...

script:
  - test -z "gofmt -s -l $(find . -type f -iname '*.go')"
  - golint -set_exit_status ./...
  - go test -v -race ./...
  - go vet ./...

notifications:
  email: false
